version: "3.3"
services:
  nginx:
    container_name: 'nginx-service'
    build:
      context: .
      dockerfile: /nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    restart: always
